### PR TITLE
PIX Payment Status selector

### PR DESCRIPTION
**Pull request by malkafly-cw**
New PIX Payment Status selector

### CODE REVIEW

**Comment by malkafly-cw** [comment]
@bru-carenzi After collecting some feedback I've created a new field on the configuration tab for the user to choose which status will be set on the PIX payment received.

**Comment by bru-carenzi** [comment]
@malkafly-cw Hi!

I believe should be better we separate the "good" status for **transactions approved** and the "negative"ones only inside the **Payment canceled**
Does not make sense we let all the status together when each of the fields has a respective kind of status to show up.

Captura de Tela 2023-05-04 às 17 56 57

**Comment by malkafly-cw** [comment]
> @malkafly-cw Hi!
> 
> I believe should be better we separate the "good" status for **transactions approved** and the "negative"ones only inside the **Payment canceled** Does not make sense we let all the status together when each of the fields has a respective kind of status to show up.
> 
> Captura de Tela 2023-05-04 às 17 56 57

This all is status from the User and/or WooCommerce installation, we cannot filter

**Review by bru-carenzi — APPROVED** [review]
### Test Report

Tests made on Staging and Production

- Test using all the status in the settings page - ok
- Card transaction - ok
- Pix transaction - ok
- Check order page to see if the status is correct - ok
- Installment transaction - ok
- Discount pix - ok

**Pull request merged**
