### PR TITLE
Adjustments on API calls 

### PR DESCRIPTION
**Pull request by malkafly-cw**
Setting user-agent on all InfinitePay API calls from PHP

### CODE REVIEW

**Review by bru-carenzi — COMMENTED** [review]
Tests on production and on staging:

@malkafly-cw  If I try to use a card to finish my purchase then returns this error: `[tokenize]: {"code":403,"message":"Forbidden"}`

Using Pix as a payment returns: Ooops, an internal error has occurred, wait bit and try again! - without status code in the log, just the confirmation that was create a order. 
```
2023-01-23T16:44:53+00:00 DEBUG New Order #609 created. Init sub order.
2023-01-23T16:44:53+00:00 DEBUG 1 vendor only, skipping sub order.
```
User to test in prod:
38 93838 3838 
Credentials:
client id: 06b6a5d937cf38a0d56a087bbb846e8e
cliente secret: 3fbc43d367b16fadd36f591de4f428210e96c0e138b53b648133d1a09d2951b2

**Comment by bru-carenzi** [comment]
@malkafly-cw it's not been possible to finalize a purchase using credit card or pix on staging, there is a problem with the API: 

```
Starting IP payment for nsu 3739148f-4e66-47e4-80e9-1e48e14a513a
01-24-2023 @ 10:23:38 - [process_credit_card]: [611] Error 500 on IP payment for nsu 3739148f-4e66-47e4-80e9-1e48e14a513a, error log: {"headers":{},"body":"{\"errors\":{\"title\":\"Internal server error - undefined method `product_id' for nil:NilClass\",\"source\":\"\/v2\/transactions\",\"status\":500}}","response":{"code":500,"message":"Internal Server Error"},"cookies":[{"name":"__cf_bm","value":"SPOOGFpfSaL8svU5WKXQDFQF7MJWSrIgpDJif.HWxA8-1674566618-0-AVQZTYs1T388VlmDG8zzXSIzvzz1Mu6kcW64BfCE67Cs1lIl2SegFwy\/mwSv2tZ 5Cj7S6VuJmpdHUdILCRCUtE=","expires":1674568418,"path":"\/","domain":"infinitepay.io","port":null,"host_only":false}],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
```
We also have the same problem to generate pix.

**Review by leonogueira-cw — APPROVED** [review]

**Comment by bru-carenzi** [comment]
@malkafly-cw the pix problem have this auth response : {:code=>403, :payload=>{"status"=>"Unauthorized! Use the DD ISO account."}}

And looks like a card transaction. This implementation [Adding order object to pix payload
](https://github.com/cloudwalk/infinitepay-woocommerce-plugin/pull/46) is not happening

**Comment by bru-carenzi** [comment]
@malkafly-cw we have a regression in the code, as u can see the print below my purchase have the value of 1,00 but return error, seems that my purchase is less than 1,00 but it does not

Captura de Tela 2023-01-26 às 09 50 07

**Review by bru-carenzi — APPROVED** [review]
### Test Summary

**Status**: 👍 Ready 

---


📋 Test report 
Insert here which tests you have done in this PR and put a ✅ [Check Mark Button](https://emojipedia.org/check-mark-button/) emoji for those tests that are validated, or put the [❌ Cross Mark](https://emojipedia.org/cross-mark/) for the tests with error.
Tests on production:

Pix transaction ✅
Credit card transaction ✅
Check order after payment ✅
Pix Discount  ✅

**Pull request merged**
