### PR TITLE
FIX: Security and PIX 

### PR DESCRIPTION
**Pull request by malkafly-cw**
Security enhancements

### CODE REVIEW

**Comment by malkafly-cw** [comment]
@bru-carenzi This is a large code update, we need to test everything again.

**Comment by bru-carenzi** [comment]
@malkafly-cw I am not able to use Pix and Card method on stg and production. Always return this error below in the checkout page : Error processing checkout. Please try again. The checkout forms is filled. 


And checking the log, the order have been created but with status Pending payment, there not error in the log. 


2023-05-18T16:46:31+00:00 DEBUG #793 - No shipping method found. Aborting.
2023-05-18T16:46:31+00:00 DEBUG Created sub order : #793
2023-05-18T16:46:31+00:00 DEBUG Completed sub order for #791.

**Review by bru-carenzi — CHANGES_REQUESTED** [review]
https://github.com/cloudwalk/infinitepay-woocommerce-plugin/pull/56#issuecomment-1553337540

**Comment by malkafly-cw** [comment]
closing this PR - the version named on branch is outdated

**Pull request closed without merging**
